//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public decimal idBitacora { get; set; }
        public Nullable<decimal> idUsuario { get; set; }
        public Nullable<decimal> IdDocumento { get; set; }
        public string vin { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string accion { get; set; }
    
        public virtual LicitacionUnidad LicitacionUnidad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
