//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public decimal idDocumento { get; set; }
        public string ruta { get; set; }
        public string vin { get; set; }
    
        public virtual LicitacionUnidad LicitacionUnidad { get; set; }
    }
}
