//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaseDocumento
    {
        public decimal idFaseDocumento { get; set; }
        public decimal idFase { get; set; }
        public decimal idDocumento { get; set; }
        public bool obligatorio { get; set; }
        public Nullable<short> orden { get; set; }
    
        public virtual CatalogoDocumento CatalogoDocumento { get; set; }
        public virtual Fase Fase { get; set; }
    }
}
