//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FlotillasEntities : DbContext
    {
        public FlotillasEntities()
            : base("name=FlotillasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Catalogo> Catalogo { get; set; }
        public virtual DbSet<CatalogoDocumento> CatalogoDocumento { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<DocumentosMultiples> DocumentosMultiples { get; set; }
        public virtual DbSet<Fase> Fase { get; set; }
        public virtual DbSet<FaseDocumento> FaseDocumento { get; set; }
        public virtual DbSet<FaseRol> FaseRol { get; set; }
        public virtual DbSet<Gps> Gps { get; set; }
        public virtual DbSet<Licitacion> Licitacion { get; set; }
        public virtual DbSet<LicitacionUnidad> LicitacionUnidad { get; set; }
        public virtual DbSet<ListaDocumentos> ListaDocumentos { get; set; }
        public virtual DbSet<Parametro> Parametro { get; set; }
        public virtual DbSet<PerfilDocumento> PerfilDocumento { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sincronizacion> Sincronizacion { get; set; }
        public virtual DbSet<SincronizacionUnidad> SincronizacionUnidad { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unidad> Unidad { get; set; }
        public virtual DbSet<UnidadAccesorio> UnidadAccesorio { get; set; }
        public virtual DbSet<UnidadAccesorioOtro> UnidadAccesorioOtro { get; set; }
        public virtual DbSet<UnidadPropiedad> UnidadPropiedad { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Valor> Valor { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> DEL_ACCESORIO_OTROS_SP(Nullable<decimal> idUnidadAccesorioOtro)
        {
            var idUnidadAccesorioOtroParameter = idUnidadAccesorioOtro.HasValue ?
                new ObjectParameter("idUnidadAccesorioOtro", idUnidadAccesorioOtro) :
                new ObjectParameter("idUnidadAccesorioOtro", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("DEL_ACCESORIO_OTROS_SP", idUnidadAccesorioOtroParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> DEL_ACCESORIO_SP(Nullable<decimal> idUnidadAccesorio)
        {
            var idUnidadAccesorioParameter = idUnidadAccesorio.HasValue ?
                new ObjectParameter("idUnidadAccesorio", idUnidadAccesorio) :
                new ObjectParameter("idUnidadAccesorio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("DEL_ACCESORIO_SP", idUnidadAccesorioParameter);
        }
    
        public virtual ObjectResult<string> DEL_UNIDAD_PROPIEDAD_SP(string vin, Nullable<decimal> idDocumento, string valor, Nullable<decimal> consecutivo)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("idDocumento", idDocumento) :
                new ObjectParameter("idDocumento", typeof(decimal));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("consecutivo", consecutivo) :
                new ObjectParameter("consecutivo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DEL_UNIDAD_PROPIEDAD_SP", vinParameter, idDocumentoParameter, valorParameter, consecutivoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> INS_ACCESORIO_OTROS_SP(Nullable<decimal> idUnidad, string descripcion)
        {
            var idUnidadParameter = idUnidad.HasValue ?
                new ObjectParameter("idUnidad", idUnidad) :
                new ObjectParameter("idUnidad", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("INS_ACCESORIO_OTROS_SP", idUnidadParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> INS_ACCESORIO_SP(Nullable<decimal> idUnidad, Nullable<decimal> idAccesorio)
        {
            var idUnidadParameter = idUnidad.HasValue ?
                new ObjectParameter("idUnidad", idUnidad) :
                new ObjectParameter("idUnidad", typeof(decimal));
    
            var idAccesorioParameter = idAccesorio.HasValue ?
                new ObjectParameter("idAccesorio", idAccesorio) :
                new ObjectParameter("idAccesorio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("INS_ACCESORIO_SP", idUnidadParameter, idAccesorioParameter);
        }
    
        public virtual int INS_BITACORA_SP(Nullable<decimal> idUsuario, string vin, string accion, Nullable<decimal> idDocumento)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("idDocumento", idDocumento) :
                new ObjectParameter("idDocumento", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_BITACORA_SP", idUsuarioParameter, vinParameter, accionParameter, idDocumentoParameter);
        }
    
        public virtual int INS_SINCRONIZACION_MAESTRO_DETALLE_SP(Nullable<decimal> idUsuario, string vin)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_SINCRONIZACION_MAESTRO_DETALLE_SP", idUsuarioParameter, vinParameter);
        }
    
        public virtual ObjectResult<string> INS_UNIDAD_PROPIEDAD_SP(string vin, Nullable<decimal> idDocumento, string valor, Nullable<decimal> idUsuario)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("idDocumento", idDocumento) :
                new ObjectParameter("idDocumento", typeof(decimal));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("INS_UNIDAD_PROPIEDAD_SP", vinParameter, idDocumentoParameter, valorParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> INS_UNIDAD_SP(string vin, string idLicitacion, string economicoInt, string domicilioEntrega)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var idLicitacionParameter = idLicitacion != null ?
                new ObjectParameter("idLicitacion", idLicitacion) :
                new ObjectParameter("idLicitacion", typeof(string));
    
            var economicoIntParameter = economicoInt != null ?
                new ObjectParameter("economicoInt", economicoInt) :
                new ObjectParameter("economicoInt", typeof(string));
    
            var domicilioEntregaParameter = domicilioEntrega != null ?
                new ObjectParameter("domicilioEntrega", domicilioEntrega) :
                new ObjectParameter("domicilioEntrega", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("INS_UNIDAD_SP", vinParameter, idLicitacionParameter, economicoIntParameter, domicilioEntregaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> INS_USUARIO_PENDIENTE_SP(Nullable<decimal> idrol, string nombreCompleto, string email, string password)
        {
            var idrolParameter = idrol.HasValue ?
                new ObjectParameter("idrol", idrol) :
                new ObjectParameter("idrol", typeof(decimal));
    
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("nombreCompleto", nombreCompleto) :
                new ObjectParameter("nombreCompleto", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("INS_USUARIO_PENDIENTE_SP", idrolParameter, nombreCompletoParameter, emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<SEL_ACCESORIO_SP_Result> SEL_ACCESORIO_SP(Nullable<decimal> idUnidad)
        {
            var idUnidadParameter = idUnidad.HasValue ?
                new ObjectParameter("idUnidad", idUnidad) :
                new ObjectParameter("idUnidad", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_ACCESORIO_SP_Result>("SEL_ACCESORIO_SP", idUnidadParameter);
        }
    
        public virtual ObjectResult<SEL_BITACORA_SP_Result> SEL_BITACORA_SP(string vin, Nullable<decimal> idDocumento)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("idDocumento", idDocumento) :
                new ObjectParameter("idDocumento", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_BITACORA_SP_Result>("SEL_BITACORA_SP", vinParameter, idDocumentoParameter);
        }
    
        public virtual ObjectResult<SEL_BUSQUEDA_FLOTILLA_APP_SP_Result> SEL_BUSQUEDA_FLOTILLA_APP_SP(string facturavin)
        {
            var facturavinParameter = facturavin != null ?
                new ObjectParameter("facturavin", facturavin) :
                new ObjectParameter("facturavin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_BUSQUEDA_FLOTILLA_APP_SP_Result>("SEL_BUSQUEDA_FLOTILLA_APP_SP", facturavinParameter);
        }
    
        public virtual ObjectResult<SEL_CLIENTES_SP_Result> SEL_CLIENTES_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_CLIENTES_SP_Result>("SEL_CLIENTES_SP");
        }
    
        public virtual ObjectResult<SEL_DETALLE_SINCRONIZACION_SP_Result> SEL_DETALLE_SINCRONIZACION_SP(Nullable<decimal> idSincronizacion)
        {
            var idSincronizacionParameter = idSincronizacion.HasValue ?
                new ObjectParameter("idSincronizacion", idSincronizacion) :
                new ObjectParameter("idSincronizacion", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_DETALLE_SINCRONIZACION_SP_Result>("SEL_DETALLE_SINCRONIZACION_SP", idSincronizacionParameter);
        }
    
        public virtual ObjectResult<SEL_DOCFASE_PERMISO_SP_Result> SEL_DOCFASE_PERMISO_SP(Nullable<decimal> idRol, Nullable<decimal> idFase)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(decimal));
    
            var idFaseParameter = idFase.HasValue ?
                new ObjectParameter("idFase", idFase) :
                new ObjectParameter("idFase", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_DOCFASE_PERMISO_SP_Result>("SEL_DOCFASE_PERMISO_SP", idRolParameter, idFaseParameter);
        }
    
        public virtual ObjectResult<SEL_FASE_PERMISO_SP_Result> SEL_FASE_PERMISO_SP(Nullable<decimal> idRol)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_FASE_PERMISO_SP_Result>("SEL_FASE_PERMISO_SP", idRolParameter);
        }
    
        public virtual ObjectResult<SEL_LICITACION_APP_SP_Result> SEL_LICITACION_APP_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_LICITACION_APP_SP_Result>("SEL_LICITACION_APP_SP");
        }
    
        public virtual ObjectResult<SEL_LISTA_DOCUMENTOS_SP_Result> SEL_LISTA_DOCUMENTOS_SP(string vin, Nullable<decimal> idDocumento)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("idDocumento", idDocumento) :
                new ObjectParameter("idDocumento", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_LISTA_DOCUMENTOS_SP_Result>("SEL_LISTA_DOCUMENTOS_SP", vinParameter, idDocumentoParameter);
        }
    
        public virtual ObjectResult<SEL_PERMISOS_SP_Result> SEL_PERMISOS_SP(Nullable<decimal> idRol, string vin)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(decimal));
    
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PERMISOS_SP_Result>("SEL_PERMISOS_SP", idRolParameter, vinParameter);
        }
    
        public virtual ObjectResult<SEL_PERMISOS_SP1_Result> SEL_PERMISOS_SP1(Nullable<decimal> idRol, string vin)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(decimal));
    
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PERMISOS_SP1_Result>("SEL_PERMISOS_SP1", idRolParameter, vinParameter);
        }
    
        public virtual ObjectResult<SEL_REPORTE_DOCUMENTO_SP_Result> SEL_REPORTE_DOCUMENTO_SP(Nullable<decimal> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_REPORTE_DOCUMENTO_SP_Result>("SEL_REPORTE_DOCUMENTO_SP", idClienteParameter);
        }
    
        public virtual ObjectResult<SEL_ROL_DOCUMENTO_SP_Result> SEL_ROL_DOCUMENTO_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_ROL_DOCUMENTO_SP_Result>("SEL_ROL_DOCUMENTO_SP");
        }
    
        public virtual ObjectResult<SEL_ROL_TODOS_SP_Result> SEL_ROL_TODOS_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_ROL_TODOS_SP_Result>("SEL_ROL_TODOS_SP");
        }
    
        public virtual ObjectResult<SEL_SINCRONIZACION_MAESTRO_DETALLE_SP_Result> SEL_SINCRONIZACION_MAESTRO_DETALLE_SP(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_SINCRONIZACION_MAESTRO_DETALLE_SP_Result>("SEL_SINCRONIZACION_MAESTRO_DETALLE_SP", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SEL_UNIDAD_PROPIEDAD_SP(string vin, Nullable<decimal> idDocumento)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("idDocumento", idDocumento) :
                new ObjectParameter("idDocumento", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SEL_UNIDAD_PROPIEDAD_SP", vinParameter, idDocumentoParameter);
        }
    
        public virtual ObjectResult<SEL_UNIDAD_SP_Result> SEL_UNIDAD_SP(string vin)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_UNIDAD_SP_Result>("SEL_UNIDAD_SP", vinParameter);
        }
    
        public virtual ObjectResult<SEL_VALIDAR_USUARIO_SP_Result> SEL_VALIDAR_USUARIO_SP(string usuario, string password)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_VALIDAR_USUARIO_SP_Result>("SEL_VALIDAR_USUARIO_SP", usuarioParameter, passwordParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UPD_ESTATUS_LICITACION_SP(string vin, Nullable<decimal> idLicitacion, string estatus)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var idLicitacionParameter = idLicitacion.HasValue ?
                new ObjectParameter("idLicitacion", idLicitacion) :
                new ObjectParameter("idLicitacion", typeof(decimal));
    
            var estatusParameter = estatus != null ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPD_ESTATUS_LICITACION_SP", vinParameter, idLicitacionParameter, estatusParameter);
        }
    
        public virtual ObjectResult<string> UPD_UNIDAD_PROPIEDAD_SP(string vin, Nullable<decimal> idDocumento, string valor, Nullable<decimal> idUsuario)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("idDocumento", idDocumento) :
                new ObjectParameter("idDocumento", typeof(decimal));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_UNIDAD_PROPIEDAD_SP", vinParameter, idDocumentoParameter, valorParameter, idUsuarioParameter);
        }
    
        public virtual int UPD_UNIDAD_SP(string vin, string economicoExt, string placa, string poliza, string tenencia, string verificacion, string permisoEspecial)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var economicoExtParameter = economicoExt != null ?
                new ObjectParameter("economicoExt", economicoExt) :
                new ObjectParameter("economicoExt", typeof(string));
    
            var placaParameter = placa != null ?
                new ObjectParameter("placa", placa) :
                new ObjectParameter("placa", typeof(string));
    
            var polizaParameter = poliza != null ?
                new ObjectParameter("poliza", poliza) :
                new ObjectParameter("poliza", typeof(string));
    
            var tenenciaParameter = tenencia != null ?
                new ObjectParameter("tenencia", tenencia) :
                new ObjectParameter("tenencia", typeof(string));
    
            var verificacionParameter = verificacion != null ?
                new ObjectParameter("verificacion", verificacion) :
                new ObjectParameter("verificacion", typeof(string));
    
            var permisoEspecialParameter = permisoEspecial != null ?
                new ObjectParameter("permisoEspecial", permisoEspecial) :
                new ObjectParameter("permisoEspecial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPD_UNIDAD_SP", vinParameter, economicoExtParameter, placaParameter, polizaParameter, tenenciaParameter, verificacionParameter, permisoEspecialParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> UPD_USUARIO_ACTIVO_SP(Nullable<decimal> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("UPD_USUARIO_ACTIVO_SP", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SEL_UNIDAD_ENCABEZADO_SP_Result> SEL_UNIDAD_ENCABEZADO_SP(string vin)
        {
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_UNIDAD_ENCABEZADO_SP_Result>("SEL_UNIDAD_ENCABEZADO_SP", vinParameter);
        }
    
        public virtual ObjectResult<SEL_VALIDAR_USUARIO_URL_SP_Result> SEL_VALIDAR_USUARIO_URL_SP(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_VALIDAR_USUARIO_URL_SP_Result>("SEL_VALIDAR_USUARIO_URL_SP", usuarioParameter);
        }
    
        public virtual ObjectResult<SEL_PERSONA_PUESTO_SP_Result> SEL_PERSONA_PUESTO_SP(Nullable<int> idPersona)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PERSONA_PUESTO_SP_Result>("SEL_PERSONA_PUESTO_SP", idPersonaParameter);
        }
    
        public virtual ObjectResult<SEL_REPORTE_DOCUMENTO_TOTAL_SP_Result> SEL_REPORTE_DOCUMENTO_TOTAL_SP(Nullable<int> idLicitacion)
        {
            var idLicitacionParameter = idLicitacion.HasValue ?
                new ObjectParameter("idLicitacion", idLicitacion) :
                new ObjectParameter("idLicitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_REPORTE_DOCUMENTO_TOTAL_SP_Result>("SEL_REPORTE_DOCUMENTO_TOTAL_SP", idLicitacionParameter);
        }
    
        public virtual ObjectResult<SEL_BUSQUEDA_FLOTILLA_SP_Result> SEL_BUSQUEDA_FLOTILLA_SP(string factura, string vin, string placa, string idLicitacion)
        {
            var facturaParameter = factura != null ?
                new ObjectParameter("factura", factura) :
                new ObjectParameter("factura", typeof(string));
    
            var vinParameter = vin != null ?
                new ObjectParameter("vin", vin) :
                new ObjectParameter("vin", typeof(string));
    
            var placaParameter = placa != null ?
                new ObjectParameter("placa", placa) :
                new ObjectParameter("placa", typeof(string));
    
            var idLicitacionParameter = idLicitacion != null ?
                new ObjectParameter("idLicitacion", idLicitacion) :
                new ObjectParameter("idLicitacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_BUSQUEDA_FLOTILLA_SP_Result>("SEL_BUSQUEDA_FLOTILLA_SP", facturaParameter, vinParameter, placaParameter, idLicitacionParameter);
        }
    }
}
