//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public decimal idParametro { get; set; }
        public decimal idTipo { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public short estatus { get; set; }
    }
}
