//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SincronizacionUnidad
    {
        public decimal idSincronizacionUnidad { get; set; }
        public decimal idSincronizacion { get; set; }
        public decimal idUnidad { get; set; }
    
        public virtual Sincronizacion Sincronizacion { get; set; }
        public virtual UnidadPropiedad UnidadPropiedad { get; set; }
    }
}
