//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Business.buscarPdf {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscaFacturasXVinOperationCompleted;
        
        private System.Threading.SendOrPostCallback MuestraFacturaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Business.Properties.Settings.Default.Business_buscarPdf_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscaFacturasXVinCompletedEventHandler BuscaFacturasXVinCompleted;
        
        /// <remarks/>
        public event MuestraFacturaCompletedEventHandler MuestraFacturaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaFacturasXVin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Documento BuscaFacturasXVin(string VIN) {
            object[] results = this.Invoke("BuscaFacturasXVin", new object[] {
                        VIN});
            return ((Documento)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaFacturasXVinAsync(string VIN) {
            this.BuscaFacturasXVinAsync(VIN, null);
        }
        
        /// <remarks/>
        public void BuscaFacturasXVinAsync(string VIN, object userState) {
            if ((this.BuscaFacturasXVinOperationCompleted == null)) {
                this.BuscaFacturasXVinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaFacturasXVinOperationCompleted);
            }
            this.InvokeAsync("BuscaFacturasXVin", new object[] {
                        VIN}, this.BuscaFacturasXVinOperationCompleted, userState);
        }
        
        private void OnBuscaFacturasXVinOperationCompleted(object arg) {
            if ((this.BuscaFacturasXVinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaFacturasXVinCompleted(this, new BuscaFacturasXVinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MuestraFactura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Documento MuestraFactura(string RFCEMISOR, string RFCRECEPTOR, string SERIE, string FOLIO) {
            object[] results = this.Invoke("MuestraFactura", new object[] {
                        RFCEMISOR,
                        RFCRECEPTOR,
                        SERIE,
                        FOLIO});
            return ((Documento)(results[0]));
        }
        
        /// <remarks/>
        public void MuestraFacturaAsync(string RFCEMISOR, string RFCRECEPTOR, string SERIE, string FOLIO) {
            this.MuestraFacturaAsync(RFCEMISOR, RFCRECEPTOR, SERIE, FOLIO, null);
        }
        
        /// <remarks/>
        public void MuestraFacturaAsync(string RFCEMISOR, string RFCRECEPTOR, string SERIE, string FOLIO, object userState) {
            if ((this.MuestraFacturaOperationCompleted == null)) {
                this.MuestraFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMuestraFacturaOperationCompleted);
            }
            this.InvokeAsync("MuestraFactura", new object[] {
                        RFCEMISOR,
                        RFCRECEPTOR,
                        SERIE,
                        FOLIO}, this.MuestraFacturaOperationCompleted, userState);
        }
        
        private void OnMuestraFacturaOperationCompleted(object arg) {
            if ((this.MuestraFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MuestraFacturaCompleted(this, new MuestraFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Documento {
        
        private byte[] pdfField;
        
        private byte[][] arrFacturasField;
        
        private string mensajeresultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        public byte[][] arrFacturas {
            get {
                return this.arrFacturasField;
            }
            set {
                this.arrFacturasField = value;
            }
        }
        
        /// <remarks/>
        public string mensajeresultado {
            get {
                return this.mensajeresultadoField;
            }
            set {
                this.mensajeresultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BuscaFacturasXVinCompletedEventHandler(object sender, BuscaFacturasXVinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaFacturasXVinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaFacturasXVinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Documento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Documento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void MuestraFacturaCompletedEventHandler(object sender, MuestraFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MuestraFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MuestraFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Documento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Documento)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591