//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.pruebaFactura {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServiceCartaFactura")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="pruebaFactura.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReport", ReplyAction="http://tempuri.org/IService1/CreateReportResponse")]
        byte[] CreateReport(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReport", ReplyAction="http://tempuri.org/IService1/CreateReportResponse")]
        System.Threading.Tasks.Task<byte[]> CreateReportAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReportChevrolet", ReplyAction="http://tempuri.org/IService1/CreateReportChevroletResponse")]
        byte[] CreateReportChevrolet(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReportChevrolet", ReplyAction="http://tempuri.org/IService1/CreateReportChevroletResponse")]
        System.Threading.Tasks.Task<byte[]> CreateReportChevroletAsync(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReportNissan", ReplyAction="http://tempuri.org/IService1/CreateReportNissanResponse")]
        byte[] CreateReportNissan(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReportNissan", ReplyAction="http://tempuri.org/IService1/CreateReportNissanResponse")]
        System.Threading.Tasks.Task<byte[]> CreateReportNissanAsync(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReportFord", ReplyAction="http://tempuri.org/IService1/CreateReportFordResponse")]
        byte[] CreateReportFord(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReportFord", ReplyAction="http://tempuri.org/IService1/CreateReportFordResponse")]
        System.Threading.Tasks.Task<byte[]> CreateReportFordAsync(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReportVW", ReplyAction="http://tempuri.org/IService1/CreateReportVWResponse")]
        byte[] CreateReportVW(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateReportVW", ReplyAction="http://tempuri.org/IService1/CreateReportVWResponse")]
        System.Threading.Tasks.Task<byte[]> CreateReportVWAsync(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDocsState", ReplyAction="http://tempuri.org/IService1/GetDocsStateResponse")]
        string[] GetDocsState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDocsState", ReplyAction="http://tempuri.org/IService1/GetDocsStateResponse")]
        System.Threading.Tasks.Task<string[]> GetDocsStateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Business.pruebaFactura.CompositeType GetDataUsingDataContract(Business.pruebaFactura.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Business.pruebaFactura.CompositeType> GetDataUsingDataContractAsync(Business.pruebaFactura.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Business.pruebaFactura.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Business.pruebaFactura.IService1>, Business.pruebaFactura.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public byte[] CreateReport(string value) {
            return base.Channel.CreateReport(value);
        }
        
        public System.Threading.Tasks.Task<byte[]> CreateReportAsync(string value) {
            return base.Channel.CreateReportAsync(value);
        }
        
        public byte[] CreateReportChevrolet(string[] data) {
            return base.Channel.CreateReportChevrolet(data);
        }
        
        public System.Threading.Tasks.Task<byte[]> CreateReportChevroletAsync(string[] data) {
            return base.Channel.CreateReportChevroletAsync(data);
        }
        
        public byte[] CreateReportNissan(string[] data) {
            return base.Channel.CreateReportNissan(data);
        }
        
        public System.Threading.Tasks.Task<byte[]> CreateReportNissanAsync(string[] data) {
            return base.Channel.CreateReportNissanAsync(data);
        }
        
        public byte[] CreateReportFord(string[] data) {
            return base.Channel.CreateReportFord(data);
        }
        
        public System.Threading.Tasks.Task<byte[]> CreateReportFordAsync(string[] data) {
            return base.Channel.CreateReportFordAsync(data);
        }
        
        public byte[] CreateReportVW(string[] data) {
            return base.Channel.CreateReportVW(data);
        }
        
        public System.Threading.Tasks.Task<byte[]> CreateReportVWAsync(string[] data) {
            return base.Channel.CreateReportVWAsync(data);
        }
        
        public string[] GetDocsState() {
            return base.Channel.GetDocsState();
        }
        
        public System.Threading.Tasks.Task<string[]> GetDocsStateAsync() {
            return base.Channel.GetDocsStateAsync();
        }
        
        public Business.pruebaFactura.CompositeType GetDataUsingDataContract(Business.pruebaFactura.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Business.pruebaFactura.CompositeType> GetDataUsingDataContractAsync(Business.pruebaFactura.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
